Repository Team-Enigma23/location-based-gourmet-recommendation-project, pull requests merged in 2023-11, with the labels that each got.

#18 Feat #1 : Client 엔티티 추가
  src/main/java/com/example/skeleton/domain/client/entity/Client.java
  src/main/java/com/example/skeleton/domain/client/entity/Location.java
  src/main/java/com/example/skeleton/domain/client/entity/Permission.java
  src/main/java/com/example/skeleton/domain/client/repository/ClientRepository.java
  src/main/java/com/example/skeleton/domain/rating/entity/Rating.java
  src/main/java/com/example/skeleton/domain/rating/repository/RatingRepository.java
Labels: enhancement

#21 Feat #7, #14 : 시군구 위, 경도 CSV 업로드 및 목록 조회 기능 구현
  src/main/java/com/example/skeleton/domain/client/entity/Location.java
  src/main/java/com/example/skeleton/domain/district/controller/DistrictController.java
  src/main/java/com/example/skeleton/domain/district/entity/District.java
  src/main/java/com/example/skeleton/domain/district/repository/DistrictRepository.java
  src/main/java/com/example/skeleton/domain/district/service/DistrictService.java
Labels: enhancement

#20 Feat #19 : swagger
  build.gradle
  src/main/java/com/example/skeleton/global/config/swagger/SwaggerConfig.java
  src/main/resources/application.yml
Labels: documentation

#23 Feat #1, #3, #4 : 회원가입, 사용자 정보 설정, 정보 조회 기능 구현
  src/main/java/com/example/skeleton/domain/client/controller/ClientController.java
  src/main/java/com/example/skeleton/domain/client/dto/ClientInfo.java
  src/main/java/com/example/skeleton/domain/client/dto/ClientRequestDto.java
  src/main/java/com/example/skeleton/domain/client/dto/ClientResponseDto.java
  src/main/java/com/example/skeleton/domain/client/entity/Client.java
  src/main/java/com/example/skeleton/domain/client/entity/Location.java
  src/main/java/com/example/skeleton/domain/client/repository/ClientRepository.java
  src/main/java/com/example/skeleton/domain/client/service/ClientService.java
  src/main/java/com/example/skeleton/domain/client/service/ClientServiceImpl.java
Labels: enhancement

#26 Feat #25 : Validation, Redis 의존성 추가
  build.gradle
Labels: enhancement

#27 데이터 처리 PR
  README.MD
  build.gradle
  src/main/java/com/example/skeleton/LocationGourmetApplication.java
  src/main/java/com/example/skeleton/domain/gourmet/entity/Gourmet.java
  src/main/java/com/example/skeleton/domain/gourmet/repository/GourmetRepository.java
  src/main/java/com/example/skeleton/global/config/SchedulerConfig.java
  src/main/java/com/example/skeleton/global/config/SecurityConfig.java
  src/main/java/com/example/skeleton/global/model/Address.java
  src/main/java/com/example/skeleton/global/model/Point.java
  src/main/java/com/example/skeleton/global/schedule/GourmetScheduleService.java
  src/main/java/com/example/skeleton/global/schedule/ScheduledTasks.java
  src/main/java/com/example/skeleton/global/schedule/WebClientService.java
  src/main/java/com/example/skeleton/global/schedule/model/OpenApiType.java
  src/main/java/com/example/skeleton/global/schedule/model/OpenApiUrlPath.java
  src/main/resources/application.yml
  src/test/java/com/example/skeleton/global/schedule/WebClientServiceTest.java
Labels: enhancement

#28 Feat #15 : SecurityConfig, TokenProvider 및 TokenAuthenticationFilter 작성
  src/main/java/com/example/skeleton/domain/client/controller/ClientController.java
  src/main/java/com/example/skeleton/global/config/jwt/JwtTokenAuthenticationFilter.java
  src/main/java/com/example/skeleton/global/config/jwt/JwtTokenProvider.java
  src/main/java/com/example/skeleton/global/config/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#31 Fix : SecurityConfig 중복 제거
  src/main/java/com/example/skeleton/global/config/SecurityConfig.java
  src/main/java/com/example/skeleton/global/config/security/SecurityConfig.java
Labels: bug

#30 Refactor #1, #3, #4, #14 : Location을 Point로 변경
  src/main/java/com/example/skeleton/domain/client/dto/ClientInfo.java
  src/main/java/com/example/skeleton/domain/client/entity/Client.java
  src/main/java/com/example/skeleton/domain/client/entity/Location.java
  src/main/java/com/example/skeleton/domain/client/service/ClientServiceImpl.java
  src/main/java/com/example/skeleton/domain/district/entity/District.java
  src/main/java/com/example/skeleton/domain/district/service/DistrictService.java
Labels: enhancement

#29 Feat #2,15 : 로그인 API 구현(로그인과 동시에 access토큰 발급)
  src/main/java/com/example/skeleton/domain/client/controller/ClientController.java
  src/main/java/com/example/skeleton/domain/client/dto/ClientRequestDto.java
  src/main/java/com/example/skeleton/domain/client/dto/ClientSignInRequestDto.java
  src/main/java/com/example/skeleton/domain/client/service/ClientServiceImpl.java
  src/main/java/com/example/skeleton/domain/client/service/ClientSignInService.java
  src/main/java/com/example/skeleton/domain/jwt/dto/AccessTokenCreationResponseDto.java
  src/main/java/com/example/skeleton/global/config/jwt/JwtTokenAuthenticationFilter.java
  src/main/resources/application.yml
  src/test/java/com/example/skeleton/domain/client/controller/ClientControllerTest.java
Labels: enhancement

#34 Feat #12 : 맛집 평가 POST API 구현
  src/main/java/com/example/skeleton/domain/client/controller/ClientController.java
  src/main/java/com/example/skeleton/domain/gourmet/entity/Gourmet.java
  src/main/java/com/example/skeleton/domain/gourmet/repository/GourmetRepository.java
  src/main/java/com/example/skeleton/domain/rating/controller/RatingController.java
  src/main/java/com/example/skeleton/domain/rating/dto/RatingRequestDto.java
  src/main/java/com/example/skeleton/domain/rating/dto/RatingResponseDto.java
  src/main/java/com/example/skeleton/domain/rating/entity/Rating.java
  src/main/java/com/example/skeleton/domain/rating/repository/RatingRepository.java
  src/main/java/com/example/skeleton/domain/rating/service/RatingService.java
  src/main/java/com/example/skeleton/domain/rating/service/RatingServiceImpl.java
Labels: enhancement

#38 Embedded entity 값 추가
  src/main/java/com/example/skeleton/domain/gourmet/entity/Gourmet.java
  src/main/java/com/example/skeleton/domain/gourmet/model/DistrictInfo.java
  src/main/java/com/example/skeleton/domain/gourmet/model/Employee.java
  src/main/java/com/example/skeleton/global/schedule/ScheduledTasks.java
  src/main/java/com/example/skeleton/global/schedule/WebClientService.java
  src/main/java/com/example/skeleton/global/schedule/model/OpenApiType.java
Labels: enhancement

#39 Scheduling Refactoring Pull Request
  src/main/java/com/example/skeleton/global/schedule/GourmetScheduleService.java
  src/main/java/com/example/skeleton/global/schedule/ScheduledTasks.java
  src/main/java/com/example/skeleton/global/schedule/WebClientService.java
Labels: enhancement

#37 Feat #32 : Redis Configuration and 시군구 데이터 캐싱
  src/main/java/com/example/skeleton/LocationGourmetApplication.java
  src/main/java/com/example/skeleton/domain/client/entity/Location.java
  src/main/java/com/example/skeleton/domain/district/controller/DistrictController.java
  src/main/java/com/example/skeleton/domain/district/entity/District.java
  src/main/java/com/example/skeleton/domain/district/repository/DistrictRepository.java
  src/main/java/com/example/skeleton/domain/district/service/DistrictService.java
  src/main/java/com/example/skeleton/global/config/redis/CacheConfig.java
  src/main/java/com/example/skeleton/global/config/redis/RedisConfig.java
  src/main/java/com/example/skeleton/global/model/Point.java
  src/main/java/com/example/skeleton/global/model/RedisCacheType.java
  src/main/resources/application.yml
  src/test/java/com/example/skeleton/domain/district/service/DistrictServiceTest.java
  src/test/java/com/example/skeleton/global/config/redis/RedisTemplateTest.java
Labels: enhancement

#36 #11 맛집 상세 정보 API
  .gitignore
  build.gradle
  src/main/java/com/example/skeleton/domain/gourmet/controller/GourmetController.java
  src/main/java/com/example/skeleton/domain/gourmet/dto/GourmetResponseDto.java
  src/main/java/com/example/skeleton/domain/gourmet/mapper/GourmetMapper.java
  src/main/java/com/example/skeleton/domain/gourmet/service/GourmetInitService.java
  src/main/java/com/example/skeleton/domain/gourmet/service/GourmetService.java
  src/main/java/com/example/skeleton/domain/rating/dto/RatingInfo.java
  src/main/java/com/example/skeleton/domain/rating/mapper/RatingMapper.java
  src/main/java/com/example/skeleton/domain/rating/repository/RatingRepository.java
Labels: enhancement

#40 Feat #13 : Discord Webhook 식당 추천 API 구현
  src/main/java/com/example/skeleton/domain/client/repository/ClientRepository.java
  src/main/java/com/example/skeleton/domain/gourmet/repository/GourmetRepository.java
  src/main/java/com/example/skeleton/global/webhook/config/DiscordWebhookConfig.java
  src/main/java/com/example/skeleton/global/webhook/dto/DiscordWebhookMessage.java
  src/main/java/com/example/skeleton/global/webhook/dto/Embed.java
  src/main/java/com/example/skeleton/global/webhook/scheduler/DiscordWebhookScheduler.java
  src/main/java/com/example/skeleton/global/webhook/service/DiscordWebhookService.java
Labels: enhancement

#42 Feat #41 : application.yml 암호화 및 외부 DB, Redis 설정
  .gitignore
  build.gradle
  src/main/java/com/example/skeleton/global/config/JasyptConfig.java
  src/main/resources/application.yml
Labels: enhancement

#45 Fix #13 : Point 필드(위도, 경도) 타입 변경, 쿼리 수정
  src/main/java/com/example/skeleton/domain/client/dto/ClientRequestDto.java
  src/main/java/com/example/skeleton/domain/client/entity/Client.java
  src/main/java/com/example/skeleton/domain/district/service/DistrictService.java
  src/main/java/com/example/skeleton/domain/gourmet/repository/GourmetRepository.java
  src/main/java/com/example/skeleton/domain/gourmet/service/GourmetInitService.java
  src/main/java/com/example/skeleton/global/model/Point.java
  src/main/java/com/example/skeleton/global/schedule/WebClientService.java
  src/main/java/com/example/skeleton/global/webhook/service/DiscordWebhookService.java
  src/test/java/com/example/skeleton/domain/district/service/DistrictServiceTest.java
Labels: bug

#47 Feat #46 : 초기 데이터 입력 설정 코드 수정
  src/main/java/com/example/skeleton/domain/gourmet/service/GourmetInitService.java
Labels: bug

#44 Feat #11 : 유저 민감한 정보 삭제
  src/main/java/com/example/skeleton/domain/client/dto/ClientSimpleInfo.java
  src/main/java/com/example/skeleton/domain/rating/dto/RatingInfo.java
Labels: enhancement

#49 Test #15 : 리프레시 토큰 테스트 개선
  src/main/java/com/example/skeleton/global/config/jwt/JwtTokenProvider.java
  src/test/java/com/example/skeleton/domain/jwt/controller/RefreshTokenControllerTest.java
Labels: enhancement

#50 #9 맛집 상세정보 고도화
  build.gradle
  src/main/java/com/example/skeleton/domain/gourmet/controller/GourmetController.java
  src/main/java/com/example/skeleton/domain/gourmet/repository/GourmetRepositoryImpl.java
  src/main/java/com/example/skeleton/domain/gourmet/service/GourmetInitService.java
  src/main/java/com/example/skeleton/domain/gourmet/service/GourmetService.java
  src/main/java/com/example/skeleton/domain/gourmet/service/RedisService.java
  src/main/java/com/example/skeleton/global/config/redis/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/com/example/skeleton/domain/gourmet/service/GourmetServiceTest.java
  src/test/java/com/example/skeleton/domain/gourmet/service/RedisServiceTest.java
Labels: enhancement
